development:
  adapter: postgresql
  encoding: unicode
  database: lesyourtesdelariviere_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: lesyourtesdelariviere_test
  pool: 5
  timeout: 5000